apiVersion: v1
kind: Service
metadata:
  name: vpromq01
spec:
  ports:
    - port: 15672
      targetPort: vpromq01-port  # Corrected to targetPort
      protocol: TCP
  selector:
    app: vpromq01
  type: ClusterIP